/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obligatorio2016.grafica;

import java.util.Enumeration;
import java.util.Hashtable;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import obligatorio2016.logica.Balneario;
import obligatorio2016.logica.Ciudad;
import obligatorio2016.logica.Cliente;
import obligatorio2016.logica.Clientes;
import obligatorio2016.logica.Compra;
import obligatorio2016.logica.ComprasCliente;
import obligatorio2016.logica.Fachada;

/**
 *
 * @author Federico
 */
public class BuscarCliente extends javax.swing.JFrame {

    /**
     * Creates new form BusarCliente
     */
    public BuscarCliente() {
        initComponents();
        setLocationRelativeTo(null);
        lblBusquedaRUT.setVisible(false);
        jtxtBusquedaRut.setVisible(false);
        lblBusquedaAño.setVisible(false);
        jtxtBusquedaAño.setVisible(false);
        lblBusquedaProducto.setVisible(false);
        jtxtBusquedaProducto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cboBusqueda = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblBusquedaRUT = new javax.swing.JLabel();
        jtxtBusquedaRut = new javax.swing.JTextField();
        lblBusquedaAño = new javax.swing.JLabel();
        jtxtBusquedaAño = new javax.swing.JTextField();
        lblBusquedaProducto = new javax.swing.JLabel();
        jtxtBusquedaProducto = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Búsqueda de Clientes");

        jLabel1.setText("Criterio de Busqueda");

        cboBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por RUT/CI", "Por Año de ingreso", "Por Producto Comprados", "Por productos no Comprados" }));
        cboBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBusquedaActionPerformed(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblBusquedaRUT.setText("Ingresar RUT/CI");

        jtxtBusquedaRut.setColumns(15);
        jtxtBusquedaRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBusquedaRutActionPerformed(evt);
            }
        });

        lblBusquedaAño.setText("Ingresar Año");

        jtxtBusquedaAño.setColumns(5);

        lblBusquedaProducto.setText("Código Producto");

        jtxtBusquedaProducto.setColumns(10);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Direcciones"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Datos", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Teléfonos"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtBusquedaAño, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBusquedaAño))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtBusquedaRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBusquedaRUT))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBusquedaProducto)
                                    .addComponent(jtxtBusquedaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cboBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBusquedaRUT)
                            .addComponent(lblBusquedaAño)
                            .addComponent(lblBusquedaProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtBusquedaRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtBusquedaAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtBusquedaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void cboBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBusquedaActionPerformed
       
        int indice;
        indice = cboBusqueda.getSelectedIndex();
        switch (indice) {
        
            case 0:
                lblBusquedaProducto.setVisible(false);
                jtxtBusquedaProducto.setVisible(false);
                lblBusquedaAño.setVisible(false);
                jtxtBusquedaAño.setVisible(false);
                lblBusquedaRUT.setVisible(true);
                jtxtBusquedaRut.setVisible(true);
                break;
                
            case 1:
                lblBusquedaProducto.setVisible(false);
                jtxtBusquedaProducto.setVisible(false);
                lblBusquedaRUT.setVisible(false);
                jtxtBusquedaRut.setVisible(false);
                lblBusquedaAño.setVisible(true);
                jtxtBusquedaAño.setVisible(true);
                break;
                
            case 2:
                 lblBusquedaRUT.setVisible(false);
                jtxtBusquedaRut.setVisible(false);
                lblBusquedaAño.setVisible(false);
                jtxtBusquedaAño.setVisible(false);
                lblBusquedaProducto.setVisible(true);
                jtxtBusquedaProducto.setVisible(true);
                break;
                
            case 3:
                lblBusquedaRUT.setVisible(false);
                jtxtBusquedaRut.setVisible(false);
                lblBusquedaAño.setVisible(true);
                jtxtBusquedaAño.setVisible(true);
                lblBusquedaProducto.setVisible(false);
                jtxtBusquedaProducto.setVisible(false);
        }
        
         
    }//GEN-LAST:event_cboBusquedaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false); 
                 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtxtBusquedaRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBusquedaRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBusquedaRutActionPerformed

    private void cargarTablasCte(Cliente cte){
        DefaultTableModel modelo = new DefaultTableModel();
        jTable1.setModel(modelo);
        
        modelo.addColumn("Datos");
        modelo.addColumn("");
        
        Object [] filaDat = new Object[2];
        filaDat[0] = "Codigo";
        filaDat[1] = cte.getRUT_CI();
        modelo.addRow(filaDat);
        
        filaDat[0] = "Nombre";
        filaDat[1] = cte.getNomCte();
        modelo.addRow(filaDat);
        
        filaDat[0] = "Apellido";
        filaDat[1] = cte.getApeCte();
        modelo.addRow(filaDat);
        
        filaDat[0] = "Fecha Ing.";
        filaDat[1] = cte.getFechaIng();
        modelo.addRow(filaDat);
        
        DefaultTableModel modeloTel = new DefaultTableModel();
        jTable2.setModel(modeloTel);
        modeloTel.addColumn("Telefonos");
        Object [] filaTel = new Object[1];
        for(int i=0; i < cte.getTelCle().getColeccion().size(); i++){
            filaTel[0] = cte.getTelCle().getColeccion().get(i).getNumTel();
            modeloTel.addRow(filaTel);
        }
        
        DefaultTableModel modeloDir = new DefaultTableModel();
        jTable3.setModel(modeloDir);
        modeloDir.addColumn("Direcciones");
        Object [] filaDir = new Object[1];
        for(int i=0; i < cte.getDirCle().getColeccion().size(); i++){
            if(cte.getDirCle().getColeccion().get(i) instanceof Ciudad){
                filaDir[0] = (cte.getDirCle().getColeccion().get(i).getNomCalle() + " " + 
                        ((Ciudad) cte.getDirCle().getColeccion().get(i)).getNumPuerta() + " esq. " +
                        cte.getDirCle().getColeccion().get(i).getEsq());
            }
            if(cte.getDirCle().getColeccion().get(i) instanceof Balneario){
               filaDir[0] = (cte.getDirCle().getColeccion().get(i).getNomCalle() + ", Manz. " + 
                        ((Balneario) cte.getDirCle().getColeccion().get(i)).getManzana() + ", Solar " +
                        ((Balneario) cte.getDirCle().getColeccion().get(i)).getSolar() + ", esq. " +
                        cte.getDirCle().getColeccion().get(i).getEsq());
            }
            modeloDir.addRow(filaDir);
        }
    }
    
    private void cargarListaCtes(Clientes ctes){
        DefaultListModel modelo = new DefaultListModel();
        Enumeration <Cliente> eCte = ctes.getColeccion().elements();
        while(eCte.hasMoreElements()){
            Cliente cte = eCte.nextElement();
            modelo.addElement(cte.getRUT_CI());
        }
        jList1.setModel(modelo);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cliente cte;
        Enumeration <Cliente> eCte;
        int anio;
        
        switch (cboBusqueda.getSelectedIndex()){
            case 0: cte = Fachada.getInstancia().getDiccioCtes().find(Long.valueOf(jtxtBusquedaRut.getText()));
                    cargarTablasCte(cte);
                    break;
                
            case 1: 
                    anio = Integer.parseInt(jtxtBusquedaAño.getText());
                    DefaultListModel modelo = new DefaultListModel();
                    eCte = Fachada.getInstancia().getDiccioCtes().getColeccion().elements();
                    
                    while(eCte.hasMoreElements()){
                        cte = eCte.nextElement();
                        int i = Integer.parseInt(cte.getFechaIng());
                        if(i == anio){
                        modelo.addElement(cte.getRUT_CI());
                        }
                    }
                    jList1.setModel(modelo);
                    break;
                    
            case 2: long codProd = Long.parseLong(jtxtBusquedaProducto.getText()); System.out.println("codProdtxt " + codProd);
                    DefaultListModel modelo2 = new DefaultListModel();
                    eCte = Fachada.getInstancia().getDiccioCtes().getColeccion().elements();
                    while(eCte.hasMoreElements()){
                        cte = eCte.nextElement(); System.out.println("size " + cte.getCompras().getColeccion().size());
                        ComprasCliente comps = cte.getCompras();
                        for(int i=0; i < comps.getColeccion().size(); i++){
                            Compra comp = comps.getColeccion().get(i);
                            System.out.println("compget " + comp.getCodProd());
                            if(comp.getCodProd() == codProd){
                                modelo2.addElement(cte.getRUT_CI());
                            }
                        }
                    }
                    jList1.setModel(modelo2);
                    break;
                    
            case 3: 
                    boolean compro;
                    anio = Integer.parseInt(jtxtBusquedaAño.getText());
                    DefaultListModel modelo3 = new DefaultListModel();
                    eCte = Fachada.getInstancia().getDiccioCtes().getColeccion().elements();
                    
                    while(eCte.hasMoreElements()){
                        cte = eCte.nextElement(); System.out.println("size " + cte.getCompras().getColeccion().size());
                        ComprasCliente comps = cte.getCompras();
                        compro = false;
                        for(int i=0; i < comps.getColeccion().size(); i++){
                            Compra comp = comps.getColeccion().get(i);
                            if(comp.getAnio() == anio){
                                compro = true;
                            }
                        }
                        if(!compro){
                            modelo3.addElement(cte.getRUT_CI());
                        }
                    }
                    jList1.setModel(modelo3);
                    break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        long codCte = Long.parseLong(String.valueOf(jList1.getSelectedValue()));
        Cliente cte = Fachada.getInstancia().findCte(codCte);
        cargarTablasCte(cte);
    }//GEN-LAST:event_jList1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboBusqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jtxtBusquedaAño;
    private javax.swing.JTextField jtxtBusquedaProducto;
    private javax.swing.JTextField jtxtBusquedaRut;
    private javax.swing.JLabel lblBusquedaAño;
    private javax.swing.JLabel lblBusquedaProducto;
    private javax.swing.JLabel lblBusquedaRUT;
    // End of variables declaration//GEN-END:variables
}
