/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obligatorio2016.grafica;

import java.util.Enumeration;
import javax.swing.table.DefaultTableModel;
import obligatorio2016.logica.Balneario;
import obligatorio2016.logica.Ciudad;
import obligatorio2016.logica.Fachada;
import obligatorio2016.logica.Proveedor;

/**
 *
 * @author Federico
 */
public class BuscarProveedor extends javax.swing.JFrame {

    /**
     * Creates new form BuscarProveedor
     */
    public BuscarProveedor() {
        initComponents();
        setLocationRelativeTo(null);
         lblBusquedaCodigo1.setVisible(false);
         jtxtBusquedaCodigo1.setVisible(false);
         lblBusquedaTelefono.setVisible(false);
         jtxtBusquedaTelefono.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboBusqueda1 = new javax.swing.JComboBox<>();
        lblBusquedaCodigo1 = new javax.swing.JLabel();
        jtxtBusquedaCodigo1 = new javax.swing.JTextField();
        lblBusquedaTelefono = new javax.swing.JLabel();
        jtxtBusquedaTelefono = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Búsqueda de Preveedores");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Criterio de Busqueda");

        cboBusqueda1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por Código", "Por Teléfono", " " }));
        cboBusqueda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBusqueda1ActionPerformed(evt);
            }
        });

        lblBusquedaCodigo1.setText("Ingrese Código");

        jtxtBusquedaCodigo1.setColumns(10);

        lblBusquedaTelefono.setText("Ingrese Teléfono");

        jtxtBusquedaTelefono.setColumns(10);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Datos", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Teléfonos"
            }
        ));
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
        }

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Direcciones"
            }
        ));
        jScrollPane4.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBusquedaCodigo1)
                            .addComponent(jtxtBusquedaCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBusquedaTelefono)
                            .addComponent(jtxtBusquedaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboBusqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(529, 529, 529))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jButton1)
                        .addGap(22, 22, 22)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cboBusqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBusquedaCodigo1)
                            .addComponent(lblBusquedaTelefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtBusquedaCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtBusquedaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false); 
               
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cboBusqueda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBusqueda1ActionPerformed

        int indice1;
        indice1 = cboBusqueda1.getSelectedIndex();
        switch (indice1) {

            case 0:
            lblBusquedaTelefono.setVisible(false);
            jtxtBusquedaTelefono.setVisible(false);
            lblBusquedaCodigo1.setVisible(true);
            jtxtBusquedaCodigo1.setVisible(true);

            break;

            case 1:
            lblBusquedaCodigo1.setVisible(false);
            jtxtBusquedaCodigo1.setVisible(false);
            lblBusquedaTelefono.setVisible(true);
            jtxtBusquedaTelefono.setVisible(true);

            break;

        }
    }//GEN-LAST:event_cboBusqueda1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = new DefaultTableModel();
        jTable1.setModel(modelo);
        Proveedor prov = null; 
        if(cboBusqueda1.getSelectedIndex() == 0){
            prov = Fachada.getInstancia().getDiccioProv().find(Long.valueOf(jtxtBusquedaCodigo1.getText()));
        }
        if(cboBusqueda1.getSelectedIndex() == 1){
            prov = Fachada.getInstancia().getProvXTel(Integer.parseInt(jtxtBusquedaTelefono.getText()));
        }
        
        modelo.addColumn("Datos");
        modelo.addColumn("");
        
        Object [] filaDat = new Object[2];
        filaDat[0] = "Codigo";
        filaDat[1] = prov.getCodProv();
        modelo.addRow(filaDat);
        
        filaDat[0] = "Nombre";
        filaDat[1] = prov.getNomProv();
        modelo.addRow(filaDat);
        
        filaDat[0] = "Contacto";
        filaDat[1] = prov.getNomCont();
        modelo.addRow(filaDat);
        
        DefaultTableModel modeloTel = new DefaultTableModel();
        jTable2.setModel(modeloTel);
        modeloTel.addColumn("Telefonos");
        Object [] filaTel = new Object[1];
        for(int i=0; i < prov.getTelProv().getColeccion().size(); i++){
            filaTel[0] = prov.getTelProv().getColeccion().get(i).getNumTel();
            modeloTel.addRow(filaTel);
        }
        
        DefaultTableModel modeloDir = new DefaultTableModel();
        jTable3.setModel(modeloDir);
        modeloDir.addColumn("Direcciones");
        Object [] filaDir = new Object[1];
        for(int i=0; i < prov.getDirProv().getColeccion().size(); i++){
            if(prov.getDirProv().getColeccion().get(i) instanceof Ciudad){
                filaDir[0] = (prov.getDirProv().getColeccion().get(i).getNomCalle() + " " + 
                        ((Ciudad) prov.getDirProv().getColeccion().get(i)).getNumPuerta() + " esq. " +
                        prov.getDirProv().getColeccion().get(i).getEsq());
            }
            if(prov.getDirProv().getColeccion().get(i) instanceof Balneario){
               filaDir[0] = (prov.getDirProv().getColeccion().get(i).getNomCalle() + ", Manz. " + 
                        ((Balneario) prov.getDirProv().getColeccion().get(i)).getManzana() + ", Solar " +
                        ((Balneario) prov.getDirProv().getColeccion().get(i)).getSolar() + ", esq. " +
                        prov.getDirProv().getColeccion().get(i).getEsq());
            }
            modeloDir.addRow(filaDir);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboBusqueda1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jtxtBusquedaCodigo1;
    private javax.swing.JTextField jtxtBusquedaTelefono;
    private javax.swing.JLabel lblBusquedaCodigo1;
    private javax.swing.JLabel lblBusquedaTelefono;
    // End of variables declaration//GEN-END:variables
}
